from enum import Enum


class GPIO(Enum):
    MOTOR_LEFT_PIN_1: 2
    MOTOR_LEFT_PIN_2: 3
    MOTOR_LEFT_PIN_3: 4
    MOTOR_LEFT_PIN_4: 17
    MOTOR_RIGHT_PIN_1: 27
    MOTOR_RIGHT_PIN_2: 22
    MOTOR_RIGHT_PIN_3: 10
    MOTOR_RIGHT_PIN_4: 9
    SENSOR_LEFT: 14
    SENSOR_MIDDLE: 15
    SENSOR_RIGHT: 18
    BUTTON: 26
